baseURL = 'https://sbecerek.github.io/'
languageCode = 'en-us'
title = 'Suheyb Becerek'
theme = 'tale'
[params]
  AuthorName = 'Suheyb Becerek'
  GitHubUser = 'sbecerek'
[permalinks]
  posts = '/:year/:month/:title/'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0